spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/projectmaic?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: local_db_pw
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      logging.level:
        org.hibernate.SQL: debug
    show-sql: true
    defer-datasource-initialization: true
  redis:
    host: localhost
    port: 6379
