spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/projectmaic?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: local_db_pw
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      logging.level:
        org.hibernate.SQL: debug
    show-sql: true
