spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maic_db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: local_db_pw
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      logging.level:
        org.hibernate.SQL: debug
    show-sql: true
  redis:
    host: localhost
    port: 6379

fcm: ${fcm}
